name: Build NodeJS application
'on': workflow_dispatch
env: 
  USER_NAME: 'PANKAJ KUMAR'
  USER_PWD: 'PASSWORD'
jobs:
  install-dependencies:
    runs-on: windows-latest
    steps:
      - name: Display envionment variable
        run: |
          echo $env:USER_NAME
          echo $env:USER_PWD
          # displaying using env context
          echo ${{ env.USER_NAME }}
      - name: Download source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: pwsh
        run: echo "dir=$(npm config get cache)" >> ${env:GITHUB_OUTPUT}
        
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install node version 16.x     
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Installing dependencies
        run: |
          npm ci
          dir
           
      - name: Build Source code
        run: npm run build
        
      - uses: actions/upload-artifact@v2
        with:
         name: dist_files
         path: dist



